# Backprogpagation Algorithm 
Backpropagation, or backward propagation of errors, is an algorithm that is designed to test for errors working back from output nodes to input nodes.

## Import modules
- `numpy` for n-dim array processing

In [2]:
import numpy as np

## Creating Dataset
A sample data is created to be trained on by the Neural Network 

In [3]:
X = np.array([
    [2, 9], 
    [1, 5], 
    [3, 9]
])

y = np.array([
    [92], 
    [86], 
    [89]
])

## Preprocessing Dataset 

In [8]:
train_x = X / np.amax(X, axis =0)
train_y = y/100

print(train_x.shape)
print(train_y)

(3, 2)
[[0.92]
 [0.86]
 [0.89]]


## Defining the Neural Network Class

In [17]:
class NeuralNetwork:
    """A Basic Neural Network with single hidden layer
    
    Attributes:
    ----------
        w1 (ndarray): The weight matrix for input to hidden layer
        w2 (ndarray): The weight matrix for hidden to output layer
    
    Methods:
    -------
        forward(X)
            Performs forward propogation and return output
            
        backward(X, y, o)
            Performs backward propogation and updates weights
            
        train(X, y)
            Runs a single training step
    """
    def __init__(self, input_size, hidden_size, output_size):
        """
        Args:
        ----
            input_size (int): The number of input units
            hidden_size (int): The number of hidden units
            output_size (int): The number of output units
        """
        np.random.seed(0) # To reproduce results
        self.input_size = input_size
        self.output_size = output_size
        self.hidden_size = hidden_size
        
        self.w1 = np.random.randn(self.input_size, self.hidden_size)
        
        self.w2 = np.random.randn(self.hidden_size, self.output_size)
        
    def forward(self, X):
        """Performs forward propogation and return output
        
        Args:
        ----
            X (ndarray): Input for the model
        Returns:
        -------
            o (ndarray): The final output of the model
        """
        
        self.z_in1 = np.dot(X, self.w1)
        
        self.z1 = self.sigmoid(self.z_in1)
        
        self.z2_in = np.dot(self.z1, self.w2)
        
        o = self.sigmoid(self.z2_in)
        
        return o
    @staticmethod
    def sigmoid(z):
        """Calculate the sigmoid activation"""
        return 1./(1+ np.exp(-z))
    
    @staticmethod
    def sigmoidPrime(z):
        """Calculates the derivate of sigmoid activation"""
        return z * (1 - z)
        
    def backward(self, X, y, o):
        """Performs backward propogation and updates weights
        Args:
        ----
            X (ndarray): Input for the model
            y (ndarray): Acutal Labels
            o (ndarray): Estimated labels
        """
        self.o_err = y - o
        self.o_delta = self.o_err * self.sigmoidPrime(o) # Sigmoid' x = x * ( 1 - x)
        
        self.z_err = self.o_delta.dot(self.w2.T)
        self.z_delta = self.z_err * self.sigmoidPrime(self.z1)
        
        self.w1 += X.T.dot(self.z_delta)
        self.w2 += self.z_in1.T.dot(self.o_delta)
        
    def train(self, X, y):
        """Performs backward propogation and updates weights
        Args:
        ----
            X (ndarray): Input for the model
            y (ndarray): Acutal Labels    
        
        """
        o = self.forward(X)
        self.backward(X, y, o)
        
        
        

## Training a Neural Network

In [35]:
nn = NeuralNetwork(2, 3, 1)
print("Inital Weights")
print("W1:\n", nn.w1)
print("W2:\n", nn.w2)

Inital Weights
W1:
 [[ 1.76405235  0.40015721  0.97873798]
 [ 2.2408932   1.86755799 -0.97727788]]
W2:
 [[ 0.95008842]
 [-0.15135721]
 [-0.10321885]]


In [36]:
for i in range(5000):
    nn.train(train_x, train_y)
    
print('Actual Output:\n', train_y)
print('Predicted Output:\n', nn.forward(train_x))

Actual Output:
 [[0.92]
 [0.86]
 [0.89]]
Predicted Output:
 [[0.90777362]
 [0.86397641]
 [0.89712377]]
