In [39]:
import numpy as np
import skfuzzy as fuzz

In [40]:
p = np.array([0.1, 0.3, 0.7, 0.4, 0.2])
q = np.array([0.1, 0.3, 0.3, 0.4, 0.5, 0.2])
t = np.array([0.1, 0.7, 0.3])

In [41]:
r = fuzz.relation_min(p, q)
print('R = p x q')
print(r)

s = fuzz.relation_min(q, t)
print('S = q x t')
print(s)

R = p x q
[[0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.3 0.3 0.3 0.3 0.2]
 [0.1 0.3 0.3 0.4 0.5 0.2]
 [0.1 0.3 0.3 0.4 0.4 0.2]
 [0.1 0.2 0.2 0.2 0.2 0.2]]
S = q x t
[[0.1 0.1 0.1]
 [0.1 0.3 0.3]
 [0.1 0.3 0.3]
 [0.1 0.4 0.3]
 [0.1 0.5 0.3]
 [0.1 0.2 0.2]]


In [42]:
print("Max min composition")
print(fuzz.maxmin_composition(r, s))

Max min composition
[[0.1 0.1 0.1]
 [0.1 0.3 0.3]
 [0.1 0.5 0.3]
 [0.1 0.4 0.3]
 [0.1 0.2 0.2]]


In [43]:
print("Max Product composition")
print(fuzz.maxprod_composition(r, s))

Max Product composition
[[0.01 0.05 0.03]
 [0.03 0.15 0.09]
 [0.05 0.25 0.15]
 [0.04 0.2  0.12]
 [0.02 0.1  0.06]]


In [52]:
def composition(rel_a, rel_b, op_a=np.max, op_b=np.min):
    assert np.shape(rel_a)[1] == np.shape(rel_b)[0], "Invalid shape for relational matrix {} {}"
    res = np.zeros(
        (np.shape(rel_a)[0], np.shape(rel_b)[1]), float
    )
    for row in range(res.shape[0]):
        for col in range(res.shape[1]):
            res[row, col] = op_b([op_a(rel_a[row]), op_a(rel_b[: , col])])

    return res

## Max Min Composition

In [53]:
res = composition(r, s)
print(res)

[[0.1 0.1 0.1]
 [0.1 0.3 0.3]
 [0.1 0.5 0.3]
 [0.1 0.4 0.3]
 [0.1 0.2 0.2]]


## Max Product Composition

In [54]:
res = composition(r, s, np.max, np.prod)
print(res)

[[0.01 0.05 0.03]
 [0.03 0.15 0.09]
 [0.05 0.25 0.15]
 [0.04 0.2  0.12]
 [0.02 0.1  0.06]]


## Min Max Composition

In [56]:
res = composition(r, s, np.min, np.max)
print(res)

[[0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]]


## Max Max Composition

In [55]:
res = composition(r, s, np.max, np.max)
print(res)

[[0.1 0.5 0.3]
 [0.3 0.5 0.3]
 [0.5 0.5 0.5]
 [0.4 0.5 0.4]
 [0.2 0.5 0.3]]


## Min Min Composition

In [57]:
res = composition(r, s, np.min, np.min)
print(res)

[[0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]]


## Max Average Composition

In [62]:
res = composition(r, s, np.max, np.mean) 
print(res)

[[0.1  0.3  0.2 ]
 [0.2  0.4  0.3 ]
 [0.3  0.5  0.4 ]
 [0.25 0.45 0.35]
 [0.15 0.35 0.25]]
